version: '3'
services:
  frontend:
    build: ./docker/frontend
    ports:
     - "5000:5000"
    volumes:
     - .:/code
  backend:
    build: ./docker/backend
    ports:
      - "3306:3306"
  redis:
    image: "redis:alpine"